/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthMainRouteImport } from './routes/_auth/main'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthSplatRouteImport } from './routes/_auth/$'
import { Route as AuthSettingUsersRouteImport } from './routes/_auth/setting/users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMainRoute = AuthMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingUsersRoute = AuthSettingUsersRouteImport.update({
  id: '/setting/users',
  path: '/setting/users',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/dashboard': typeof AuthDashboardRoute
  '/main': typeof AuthMainRoute
  '/setting/users': typeof AuthSettingUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthSplatRoute
  '/dashboard': typeof AuthDashboardRoute
  '/main': typeof AuthMainRoute
  '/setting/users': typeof AuthSettingUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$': typeof AuthSplatRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/main': typeof AuthMainRoute
  '/_auth/setting/users': typeof AuthSettingUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$' | '/dashboard' | '/main' | '/setting/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$' | '/dashboard' | '/main' | '/setting/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/$'
    | '/_auth/dashboard'
    | '/_auth/main'
    | '/_auth/setting/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/main': {
      id: '/_auth/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthMainRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/$': {
      id: '/_auth/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/setting/users': {
      id: '/_auth/setting/users'
      path: '/setting/users'
      fullPath: '/setting/users'
      preLoaderRoute: typeof AuthSettingUsersRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSplatRoute: typeof AuthSplatRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMainRoute: typeof AuthMainRoute
  AuthSettingUsersRoute: typeof AuthSettingUsersRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSplatRoute: AuthSplatRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMainRoute: AuthMainRoute,
  AuthSettingUsersRoute: AuthSettingUsersRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
